// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy5rKpWRiMt0-WFubwxxBWpWx67lZCTfw',
    appId: '1:207512687007:web:18321cd074173cdff6adaa',
    messagingSenderId: '207512687007',
    projectId: 'wanwancafe-96bba',
    authDomain: 'wanwancafe-96bba.firebaseapp.com',
    storageBucket: 'wanwancafe-96bba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu4W5ItNFZ4a1EYw-SvQaRLATCc3EdX4o',
    appId: '1:207512687007:android:d872cefbd359e147f6adaa',
    messagingSenderId: '207512687007',
    projectId: 'wanwancafe-96bba',
    storageBucket: 'wanwancafe-96bba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1sgLJArCRCSrn_sLtXIFbMM6JdeIj2Po',
    appId: '1:207512687007:ios:cb59a61a04c04e44f6adaa',
    messagingSenderId: '207512687007',
    projectId: 'wanwancafe-96bba',
    storageBucket: 'wanwancafe-96bba.firebasestorage.app',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1sgLJArCRCSrn_sLtXIFbMM6JdeIj2Po',
    appId: '1:207512687007:ios:cb59a61a04c04e44f6adaa',
    messagingSenderId: '207512687007',
    projectId: 'wanwancafe-96bba',
    storageBucket: 'wanwancafe-96bba.firebasestorage.app',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy5rKpWRiMt0-WFubwxxBWpWx67lZCTfw',
    appId: '1:207512687007:web:7c26655c8046b10ff6adaa',
    messagingSenderId: '207512687007',
    projectId: 'wanwancafe-96bba',
    authDomain: 'wanwancafe-96bba.firebaseapp.com',
    storageBucket: 'wanwancafe-96bba.firebasestorage.app',
  );

}